;; -*- lexical-binding: t; -*-
(deftheme functional-contrast-dragonized
  "Created 2026-09-01.
Port of the DR460NIZED look (KDE Sweet color scheme + the caelestia/Hyprland
dragonized scheme) onto the functional-contrast face set from the midnight
theme.  Base is Sweet's dark blue-grey (#161925), the signature accent is the
Sweet magenta (#c50ed2), and the syntax colors come from the dragonized
terminal palette: red #ed254e, green #71f79f, yellow #f9dc5c, blue #5294e2,
cyan #00c1e4, teal #00e5c3, sky #5ce6ff, lavender #7cb7ff, pink #e18de9,
peach #f9a03f.")

(setq
 bg-color "#161925"
 solaire-bg "#0e1019"
 )

(custom-theme-set-faces
 'functional-contrast-dragonized
 '(border ((t (:background "#2b3147"))))
 '(button ((t (:inherit link :underline t))))
 '(company-web-doc-attribute-face ((t (:inherit (font-lock-type-face)))))
 '(cursor ((t (:background "#c50ed2" :foreground "#161925" :inverse-video t))))
 '(custom-button ((t (:background "#0e1019" :foreground "#e18de9" :box (:line-width (1 . 1) :color "#e18de9" :style released-button)))))
 '(custom-button-mouse ((t (:box (:line-width (2 . 2) :style released-button) :foreground "black" :background "#90099b" :weight bold))))
 '(custom-face-tag ((t (:inherit custom-variable-tag :foreground "#5294e2"))))
 '(custom-link ((t (:inherit (link)))))
 '(dap-ui-marker-face ((t (:extend t :background "#4a4118"))))
 '(diff-added ((t (:inherit magit-diff-added))))
 '(diff-file-header ((t (:inherit magit-diff-hunk-heading))))
 '(diff-function ((t (:inherit magit-diff-hunk-heading-highlight))))
 '(diff-header ((t (:inherit magit-diff-hunk-heading))))
 '(diff-hunk-header ((t (:inherit magit-diff-hunk-heading-highlight))))
 '(diff-refine-added ((t (:inherit magit-diff-added-highlight))))
 '(diff-refine-removed ((t (:inherit magit-diff-removed-highlight))))
 '(diff-removed ((t (:inherit magit-diff-removed))))
 '(ediff-current-diff-A ((t (:extend t :background "#331019"))))
 '(ediff-current-diff-B ((t (:extend t :background "#0e2b1a"))))
 '(ediff-current-diff-C ((t (:extend t :background "#2e2a0e"))))
 '(ediff-even-diff-A ((t (:extend t :background "#12141f" :distant-foreground "White"))))
 '(ediff-even-diff-B ((t (:extend t :background "#12141f" :distant-foreground "White"))))
 '(ediff-even-diff-C ((t (:extend t :background "#12141f" :distant-foreground "White"))))
 '(ediff-fine-diff-A ((t (:background "#5d1c31"))))
 '(ediff-fine-diff-B ((t (:background "#1e4d33"))))
 '(ediff-fine-diff-C ((t (:background "#4d451c"))))
 '(ediff-odd-diff-A ((t (:extend t :background "#0e1019"))))
 '(ediff-odd-diff-B ((t (:extend t :background "#0e1019"))))
 '(ediff-odd-diff-C ((t (:extend t :background "#0e1019"))))
 '(escape-glyph ((t (:foreground "#767b87"))))
 '(fixed-pitch ((t (:family "Fira Code"))))
 '(font-lock-builtin-face ((t (:foreground "#e05df0" :weight normal))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#767b87" :inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:slant normal :foreground "#636873"))))
 '(font-lock-constant-face ((t (:foreground "#7cb7ff"))))
 '(font-lock-doc-face ((t (:foreground "#f9dc5c" :inherit (font-lock-comment-face)))))
 '(font-lock-function-name-face ((t (:weight bold :foreground "#71f79f" :inherit bold))))
 '(font-lock-keyword-face ((t (:weight normal :slant normal :foreground "#e05df0" :inherit (bold)))))
 '(font-lock-negation-char-face ((t (:weight bold :foreground "#f9dc5c" :inherit (bold)))))
 '(font-lock-preprocessor-face ((t (:inherit bold :foreground "#e05df0"))))
 '(font-lock-regexp-grouping-backslash ((t (:weight normal :foreground "#7cb7ff" :inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:weight normal :foreground "#f9dc5c" :inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#00e5c3"))))
 '(font-lock-type-face ((t (:foreground "#00c1e4" :slant italic :weight bold))))
 '(font-lock-variable-name-face ((t (:foreground "#5294e2"))))
 '(font-lock-warning-face ((t (:inherit warning :background "#232841" :foreground "#f9a03f" :underline t :slant italic :weight bold))))
 '(fringe ((t (:background "#0e1019" :foreground "#d3dae3"))))
 '(diff-hl-insert ((t (:background "#1e4d33" :foreground "#1e4d33"))))
 '(diff-hl-delete ((t (:background "#5d1c31" :foreground "#5d1c31"))))
 '(diff-hl-change ((t (:background "goldenrod4" :foreground "goldenrod4"))))
 '(haskell-constructor-face ((t (:inherit font-lock-type-face :foreground "#e18de9"))))
 '(haskell-operator-face ((t (:inherit font-lock-variable-name-face :foreground "#e05df0"))))
 '(haskell-type-face ((t (:inherit font-lock-type-face))))
 '(header-line ((t (:box (:line-width 1 :color "#545863") :foreground "#d3dae3" :background "#0e1019" :inherit (mode-line)))))
 '(helm-ff-directory ((t (:extend t :foreground "#5294e2"))))
 '(helm-ff-dirs ((t (:inherit font-lock-function-name-face :extend t))))
 '(helm-ff-file ((t (:extend t :foreground "#7cb7ff"))))
 '(helm-grep-file ((t (:underline (:color foreground-color :style line :position line) :extend t :foreground "#c50ed2"))))
 '(helm-header ((t (:extend t :background "#90099b"))))
 '(helm-selection ((t (:extend t :background "#2c1030" :distant-foreground "black" :foreground "LavenderBlush2"))))
 '(highlight ((t (:background "#2c1030"))))
 '(highlight-indentation-face ((t (:background "#0e1019"))))
 '(highlight-numbers-number ((t (:foreground "#ff5c7a"))))
 '(hl-line ((t (:background "#2c1030" :extend t))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(imenu-list-entry-face ((t (:foreground "gainsboro"))))
 '(isearch ((t (:inherit region :background "#f9dc5c" :foreground "#161925" :box (:line-width 2 :color "#ffe97e")))))
 '(isearch-fail ((t (:weight bold :foreground "#ed254e" :background "#161925" :inherit (isearch)))))
 '(kubernetes-namespace ((t (:foreground "#5294e2"))))
 '(lazy-highlight ((t (:weight normal :background "#3d414d" :inherit (highlight)))))
 '(line-number-current-line ((t (:inherit line-number :foreground "white"))))
 '(link ((t (:foreground "#5ce6ff" :underline t :weight bold))))
 '(link-visited ((t (:weight normal :underline (:color foreground-color :style line) :foreground "#7cb7ff"))))
 '(lsp-ui-doc-background ((((background light)) (:background "#b3b3b3")) (t (:background "#1c2030"))))
 '(lsp-ui-doc-highlight-hover ((t (:inherit (region)))))
 '(lsp-ui-peek-filename ((t (:foreground "#f9a03f"))))
 '(lsp-ui-peek-footer ((t (:inherit lsp-ui-peek-header))))
 '(lsp-ui-peek-header ((t (:background "#181b28" :foreground "#5294e2"))))
 '(lsp-ui-peek-highlight ((t (:background: "#1c2030" :foreground "grey80" :box (:line-width (1 . -1) :color "red")))))
 '(lsp-ui-peek-line-number ((t (:foreground "grey25"))))
 '(lsp-ui-peek-list ((t (:background "#181b28"))))
 '(lsp-ui-peek-peek ((t (:background "#0e1019"))))
 '(lsp-ui-peek-selection ((t (:background "#90099b"))))
 '(magit-blame-highlight ((t (:extend t :background "#1c2030" :foreground "#e18de9" :box (:line-width (1 . 1) :color "grey50" :style pressed-button)))))
 '(magit-diff-added ((t (:extend t :background "#122318" :foreground "springgreen4"))))
 '(magit-diff-added-highlight ((t (:extend t :background "#1e4d33" :foreground "SpringGreen3" :weight semi-bold))))
 '(magit-diff-context ((t (:extend t :background "#161925" :foreground "#545863"))))
 '(magit-diff-context-highlight ((t (:extend t :background "#1c2030" :foreground "#7cb7ff"))))
 '(magit-diff-hunk-heading ((t (:extend t :background "#232841" :foreground "grey80"))))
 '(magit-diff-hunk-heading-highlight ((t (:extend t :background "#90099b" :foreground "white"))))
 '(magit-diff-removed ((t (:extend t :background "#33101a" :foreground "firebrick4"))))
 '(magit-diff-removed-highlight ((t (:extend t :background "#5d1c31" :foreground "#ff5c7a" :weight semi-bold))))
 '(magit-diff-revision-summary ((t (:extend t :background "#2c1030" :foreground "#e18de9" :weight bold))))
 '(magit-diffstat-added ((t (:foreground "dark green"))))
 '(magit-diffstat-removed ((t (:foreground "dark red"))))
 '(magit-filename ((t (:foreground "#f9a03f" :weight normal))))
 '(magit-section-heading ((t (:extend t :foreground "#71f79f" :weight bold))))
 '(magit-section-highlight ((t (:extend t :background "#2c1030"))))
 '(match ((t (:weight bold :box nil :foreground "gray90" :background "#1d4f8c"))))
 '(minibuffer-prompt ((t (:foreground "#5ce6ff" :inherit (bold)))))
 '(mode-line ((t (:box (:line-width 1 :color "#545863") :foreground "#d3dae3" :background "#1c2030" :inherit region))))
 '(mode-line-buffer-id ((t (:weight bold :foreground "#71f79f" :inherit bold))))
 '(mode-line-emphasis ((t (:weight bold :foreground "#FCFCFA" :background "#ed254e"))))
 '(mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button) :foreground "#e18de9" :inherit highlight))))
 '(mode-line-inactive ((t (:box (:line-width 1 :color "#0e1019") :foreground "#666a73" :background "#0e1019"))))
 '(next-error ((t (:inherit (region)))))
 '(org-kbd ((t (:inherit custom-button))))
 '(powerline-active0 ((t (:inherit mode-line))))
 '(powerline-active1 ((t (:inherit mode-line :foreground "white"))))
 '(powerline-active2 ((t (:background "#90099b"))))
 '(powerline-inactive0 ((t (:inherit mode-line-inactive))))
 '(powerline-inactive1 ((t (:background "#1c2030" :inherit mode-line-inactive))))
 '(powerline-inactive2 ((t (:background "#45104a"))))
 '(query-replace ((t (:inherit (isearch)))))
 '(region ((t (:inherit highlight :extend t :background "#90099b"))))
 '(secondary-selection ((t (:inherit region :extend t :background "#3d414d"))))
 '(shadow ((t (:foreground "#767b87"))))
 '(show-paren-match ((t (:underline t))))
 '(smerge-base ((t (:inherit ediff-current-diff-C))))
 '(smerge-lower ((t (:inherit ediff-current-diff-B))))
 '(smerge-refined-added ((t (:inherit ediff-fine-diff-B))))
 '(smerge-refined-changed ((t nil)))
 '(smerge-refined-removed ((t (:inherit ediff-fine-diff-A))))
 '(smerge-upper ((t (:inherit ediff-current-diff-A))))
 '(solaire-default-face ((t (:inherit default :background "#0e1019"))))
 '(solaire-header-line-face ((t (:inherit default :background "#0e1019"))))
 '(ein:codecell-input-area-face ((t (:extend t :background "#0e1019"))))
 '(sp-show-pair-match-face ((t (:inherit (show-paren-match)))))
 '(sp-wrap-overlay-face ((t nil)))
 '(spaceline-evil-emacs ((t (:inherit 'mode-line :foreground "#161925" :background "SkyBlue2"))))
 '(spaceline-evil-normal ((t (:background "#90099b" :foreground "light grey"))))
 '(spaceline-evil-replace ((t (:inherit 'mode-line :foreground "#161925" :background "#f9a03f"))))
 '(spaceline-highlight-face ((t (:background "#2c1030" :foreground "light gray"))))
 '(spaceline-modified ((t (:inherit 'mode-line :foreground "#161925" :background "SkyBlue2"))))
 '(spacemacs-normal-face ((t (:background "#90099b" :foreground "light gray"))))
 '(tooltip ((t (:weight normal :slant normal :underline nil :foreground "#d3dae3" :background "#0e1019" :inherit (default)))))
 '(trailing-whitespace ((t (:background "#90099b"))))
 '(tree-sitter-hl-face:constant ((default (:inherit (font-lock-constant-face)))))
 '(tree-sitter-hl-face:constructor ((t (:foreground "#f9dc5c" :weight semi-bold))))
 '(tree-sitter-hl-face:doc ((t (:inherit (font-lock-doc-face)))))
 '(tree-sitter-hl-face:embedded ((default (:inherit (default)))))
 '(tree-sitter-hl-face:function ((t (:inherit font-lock-function-name-face))))
 '(tree-sitter-hl-face:function.builtin ((t (:foreground "#00e5c3"))))
 '(tree-sitter-hl-face:function.call ((t (:foreground "#71f79f"))))
 '(tree-sitter-hl-face:attribute ((t (:foreground "#71f79f"))))
 '(tree-sitter-hl-face:function.special ((t (:inherit (font-lock-preprocessor-face)))))
 '(tree-sitter-hl-face:keyword ((t (:foreground "#c50ed2"))))
 '(tree-sitter-hl-face:label ((default (:inherit (font-lock-preprocessor-face)))))
 '(tree-sitter-hl-face:property ((t (:inherit font-lock-constant-face :foreground "#f9dc5c" :slant italic))))
 '(tree-sitter-hl-face:property.definition ((t (:foreground "#f9dc5c"))))
 '(tree-sitter-hl-face:punctuation.bracket ((t (:inherit rainbow-delimiters-depth-1-face))))
 '(tree-sitter-hl-face:string ((t (:inherit font-lock-string-face))))
 '(tree-sitter-hl-face:string.special ((t (:inherit tree-sitter-hl-face:string :weight bold))))
 '(tree-sitter-hl-face:type ((t (:foreground "#00c1e4" :inherit font-lock-type-face))))
 '(tree-sitter-hl-face:tag ((t (:foreground "#00c1e4" :inherit font-lock-type-face))))
 '(tree-sitter-hl-face:type.argument ((t (:foreground "#7cb7ff"))))
 '(tree-sitter-hl-face:type.builtin ((t (:inherit font-lock-builtin-face :foreground "#e18de9" :weight semi-bold))))
 '(tree-sitter-hl-face:type.super ((t (:foreground "#e18de9" :weight bold))))
 '(tree-sitter-hl-face:variable ((t (:inherit font-lock-variable-name-face))))
 '(tree-sitter-hl-face:variable.builtin ((t (:foreground "#ff5c7a"))))
 '(tree-sitter-hl-face:variable.parameter ((t (:foreground "#f9a03f"))))
 '(tree-sitter-hl-face:label ((t (:foreground "#f9a03f"))))
 '(variable-pitch ((t (:family "Inconsolata" :height 1.1))))
 '(vertical-border ((((type tty)) (:inherit (mode-line-inactive)))))
 '(web-mode-html-attr-name-face ((t (:foreground "#71f79f"))))
 '(web-mode-html-tag-face ((t (:foreground "#5294e2"))))
 '(web-mode-jsx-depth-1-face ((t (:background "#101b33"))))
 '(whitespace-empty ((t nil)))
 '(whitespace-indentation ((t (:foreground "#2b3147"))))
 '(whitespace-line ((t nil)))
 '(whitespace-newline ((t (:foreground "#2b3147" :weight normal))))
 '(whitespace-space ((t (:foreground "#2b3147"))))
 '(whitespace-space-before-tab ((t (:inherit whitespace-space))))
 '(whitespace-tab ((t (:foreground "#2b3147"))))
 '(whitespace-trailing ((t (:inherit magit-diff-removed :weight bold))))
 '(widget-field ((t (:extend t :background "#0e1019" :foreground "gray"))))
 '(line-number ((t (:background "#0e1019" :foreground "#545863"))))
 ;; Headings (canonical set, shared by all functional-contrast themes).
 ;; outline-N carries the attributes and org-level-N inherits from it -- the
 ;; direction org itself uses.  Defining outline-N in terms of org-level-N
 ;; instead loops (org's own defface has org-level-N inherit outline-N), which
 ;; is the "cyclic face inheritance" error.
 '(outline-1 ((t (:foreground "#e18de9" :height 1.4 :weight bold :inherit variable-pitch))))
 '(outline-2 ((t (:foreground "#00e5c3" :height 1.2))))
 '(outline-3 ((t (:foreground "#f9dc5c" :height 1.1))))
 '(outline-4 ((t (:foreground "#00c1e4"))))
 '(outline-5 ((t (:foreground "#f9dc5c"))))
 '(outline-6 ((t (:foreground "#71f79f"))))
 '(outline-7 ((t (:foreground "#e18de9"))))
 '(outline-8 ((t (:foreground "#00c1e4"))))
 '(org-document-title ((t (:inherit outline-1))))
 '(org-document-info ((t (:inherit outline-2))))
 '(org-level-1 ((t (:inherit outline-1))))
 '(org-level-2 ((t (:inherit outline-2))))
 '(org-level-3 ((t (:inherit outline-3))))
 '(org-level-4 ((t (:inherit outline-4))))
 '(org-level-5 ((t (:inherit outline-5))))
 '(org-level-6 ((t (:inherit outline-6))))
 '(org-level-7 ((t (:inherit outline-7))))
 '(org-level-8 ((t (:inherit outline-8))))
 '(org-todo ((t (:foreground "#ed254e"))))
 '(org-done ((t (:foreground "#71f79f"))))
 '(org-headline-done ((t (:foreground "#636873"))))
 '(org-meta-line ((t (:foreground "#636873" :background "#0e1019" :extend t))))
 '(org-document-info-keyword ((t (:foreground "#636873" :extend t))))
 '(org-drawer ((t (:foreground "#636873" :extend t))))
 '(org-block-begin-line ((t (:foreground "#636873" :background "#0e1019" :extend t))))
 '(org-modern-internal-target ((t (:foreground "white" :background "#0e1019" :extend t))))
 '(org-block ((t (:foreground "white" :background "#0e1019" :extend t :inherit fixed-pitch :family "Fira Code"))))
 '(org-code ((t (:foreground "#f9dc5c" :background "#0e1019" :extend t :inherit fixed-pitch :family "Fira Code"))))
 '(org-verbatim ((t (:foreground "#f9dc5c" :background "#0e1019" :extend t))))
 '(org-superstar-item ((t (:foreground "#ffe97e"))))
 '(org-table ((t (:foreground "gray85" :background "#0e1019"))))
 ;; Markdown mirrors org-mode: same sizes, colors and fonts.
 '(markdown-header-face ((t (:inherit org-level-1))))
 '(markdown-header-face-1 ((t (:inherit org-level-1))))
 '(markdown-header-face-2 ((t (:inherit org-level-2))))
 '(markdown-header-face-3 ((t (:inherit org-level-3))))
 '(markdown-header-face-4 ((t (:inherit org-level-4))))
 '(markdown-header-face-5 ((t (:inherit org-level-5))))
 '(markdown-header-face-6 ((t (:inherit org-level-6))))
 '(markdown-header-delimiter-face ((t (:inherit org-meta-line))))
 '(markdown-header-rule-face ((t (:inherit org-meta-line))))
 '(markdown-hr-face ((t (:inherit org-meta-line))))
 '(markdown-markup-face ((t (:inherit org-meta-line))))
 '(markdown-line-break-face ((t (:inherit org-meta-line))))
 '(markdown-metadata-key-face ((t (:inherit org-document-info-keyword))))
 '(markdown-metadata-value-face ((t (:inherit org-document-info))))
 '(markdown-language-keyword-face ((t (:inherit org-block-begin-line))))
 '(markdown-language-info-face ((t (:inherit org-block-begin-line))))
 '(markdown-code-face ((t (:inherit org-block))))
 '(markdown-pre-face ((t (:inherit org-block))))
 '(markdown-inline-code-face ((t (:inherit org-verbatim))))
 '(markdown-table-face ((t (:inherit org-table))))
 '(markdown-link-face ((t (:inherit org-link))))
 '(markdown-link-title-face ((t (:inherit org-link))))
 '(markdown-url-face ((t (:inherit org-link))))
 '(markdown-plain-url-face ((t (:inherit org-link))))
 '(markdown-list-face ((t (:inherit org-superstar-item))))
 '(markdown-blockquote-face ((t (:inherit org-quote))))
 '(markdown-gfm-checkbox-face ((t (:inherit org-checkbox))))
 '(markdown-highlighting-face ((t (:inherit highlight))))
 '(markdown-bold-face ((t (:inherit bold))))
 '(markdown-italic-face ((t (:inherit italic))))
 '(markdown-html-tag-name-face ((t (:foreground "#71f79f"))))
 '(default ((t (:inherit nil :extend nil :stipple nil :background "#161925" :foreground "#d3dae3" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "CTDB" :family "Fira Code"))))
 )

(setq pdf-view-midnight-colors (cons "#d3dae3" solaire-bg))

(provide-theme 'functional-contrast-dragonized)
